import Head from 'next/head'
import Card from '../components/card'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"></link>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Raleway:wght@700&display=swap" rel="stylesheet"></link>
      </Head>

      <div className="container lg:flex lg:flex-row md:flex-col sm:flex-col mx-auto w-full h-full">
        <Card classname="card-left lg:w-2/3" backgroundColor="bg-card-left">

          <div className="pic-container flex flex-col justify-end relative h-full font-raleway">
            <div className="flex flex-row justify-between items-center p-3 z-10">
              <span className="w-150">because your business needs a lot more</span>
              <div className="flex flex-row justify-between w-150 text-xs border border-black rounded-3xl p-1">
                <span className="">get expert advise</span>
                <div className="flex flex-col items-center bg-black rounded-full w-3"><span className="text-white text-xs">{'>'}</span></div>
              </div>
            </div>
          </div>

        </Card>
        <Card classname="card-right lg:w-1/3" backgroundColor="bg-card-right" >

          <div className="flex flex-col justify-center items-center h-full font-dancing p-3">
            <span className="text-3xl">the</span>
            <span className="text-3xl font-raleway mb-1">Future</span>
            <div className="flex middle-pic w-full h-full"></div>
            <div className="font-raleway mt-1"><span className="font-thin">Free your mind for something </span><span className="font-bold font-roboto">more important</span></div>
          </div>

        </Card>
      </div>

    </div>
  )
}
